import {MarkdownView, setIcon, WorkspaceLeaf} from 'obsidian';
import {OpenAPIPluginContext} from "../contextManager";
import {PowerOffEvent, UIPluginSettings} from '../typing/interfaces'
import {eventID, SERVER_ICON_NAME_OFF, SERVER_ICON_NAME_ON} from "../typing/types";
import {ButtonFactory} from "./buttonFactory";
import {ButtonManager} from "./buttonManager";
import {Button} from "./Button";

/**
 * UIManager class manages the user interface elements related to OpenAPI Renderer Plugin in Obsidian.
 */
export default class UIManager {
    private buttonManager: ButtonManager;
    private buttonFactory: ButtonFactory;
    appContext!: OpenAPIPluginContext

    constructor(appContext: OpenAPIPluginContext) {
        this.appContext = appContext;
        this.buttonManager = new ButtonManager(this);
        this.buttonFactory = new ButtonFactory(this);
    }

    /**
     * Initializes the UI manager when the Obsidian workspace layout is ready.
     * Binds the `initializeUIManager` method to handle UI initialization tasks.
     */
    async initializeUI() {
        this.appContext.app.workspace.onLayoutReady(this.initializeUIManager.bind(this))
    }


    /**
     * Initializes the UI manager by creating all buttons, registering events,
     * and registering a cleanup handler for button removal.
     *
     * @private
     */
    private async initializeUIManager() {
        await this.createAllButtons();
        this.registerEvents();
        this.appContext.plugin.observer.subscribe(
            this.appContext.app.workspace,
            eventID.PowerOff,
            this.onunload.bind(this)
        )


    }

    async onunload(event: PowerOffEvent) {
        await this.buttonManager.removeAllButtons()
    }

    get settings(): UIPluginSettings {
        const {settings} = this.appContext.plugin
        return {
            isCreateServerButton: settings.isCreateServerButton,
            isCreateCommandButtons: settings.isCreateCommandButtons,
            serverButtonLocations: settings.serverButtonLocations,
            renderButtonLocation: settings.renderButtonLocation,
            refreshButtonLocation: settings.refreshButtonLocation

        } as UIPluginSettings;
    }


    /**
     * Creates all buttons using configurations generated by the ButtonFactory.
     * This method fetches all button configurations and creates the buttons asynchronously.
     *
     * @private
     */
    private async createAllButtons() {
        debugger
        const configs = this.buttonFactory.createAllButtonConfigs();
        await Promise.all(configs.map(config => this.buttonManager.createButton(config)))
    }

    /**
     * Toggles the server's running state based on the current state and updates UI elements accordingly.
     * @param event - The MouseEvent object representing the click event on the server button.
     */
    async toggleServer(event: MouseEvent) {
        const button = event.currentTarget as HTMLElement;
        const isRunning = this.appContext.plugin.server.isRunning();
        const view = this.appContext.app.workspace.getActiveViewOfType(MarkdownView);

        if (isRunning) {
            const isStopped = await this.appContext.plugin.server.stop();
            this.updateServerButtonIcon(!isStopped, button);
            isStopped && this.appContext.plugin.showNotice(`Server stopped.`);
            view && this.appContext.plugin.previewHandler.rerenderPreview(view);
        } else {
            view && this.appContext.plugin.previewHandler.rerenderPreview(view);
            const isStarted = await this.appContext.plugin.server.start();
            this.updateServerButtonIcon(isStarted, button);
            const msg = isStarted ? 'Server started' : 'Cannot start the server... Try again';
            this.appContext.plugin.showNotice(msg);
        }
    }

    /**
     * Updates the icon and tooltip of the server button based on its running state.
     * @param isRunning - Indicates whether the server is currently running.
     * @param button - The HTML element of the server button to update.
     */
    updateServerButtonIcon(isRunning: boolean, button: HTMLElement) {
        const iconName = isRunning ? SERVER_ICON_NAME_ON : SERVER_ICON_NAME_OFF;
        const tooltip = `Toggle OpenAPI Renderer Server ${isRunning ? 'Off' : 'On'}`
        setIcon(button, iconName);
        button.setAttribute('aria-label', tooltip);
        button.setAttribute('data-tooltip', tooltip);
    }

    /**
     * Registers event listeners for updating toolbar buttons and managing button subscriptions.
     * - Listens for active leaf changes to update the toolbar.
     * - Subscribes to button events for managing their state and behavior.
     */
    private registerEvents() {
        this.appContext.plugin.registerEvent(
            this.appContext.app.workspace.on('active-leaf-change', async (leaf) => {
                if (leaf?.view instanceof MarkdownView) {
                    await this.updateToolbar(leaf)
                }
            })
        );
        this.buttonManager.buttons.forEach((button: Button) => {
            button.subscribe()
        });
    }


    /**
     * Updates the toolbar buttons for the given workspace leaf if it is a Markdown view.
     * Removes all existing toolbar buttons and creates new ones based on the current configurations.
     *
     * @param leaf - The workspace leaf to update the toolbar for.
     */
    async updateToolbar(leaf: WorkspaceLeaf | null) {
        await this.buttonManager.updateToolbar(leaf!)
    }
}

